#!/bin/sh

#Print some Debug
set -xe

RUN_USER="worker"

#################################################
# Add worker user with specific User & Group ID #
#################################################

getent group $RUN_USER || addgroup -g $GID $RUN_USER
id -u $RUN_USER &>/dev/null || adduser -D -s /bin/sh -g $GID -G $RUN_USER -h "/home/$RUN_USER" -u $UID $RUN_USER

####################################
#Fix mounted directory permissions #
####################################
chown -R $RUN_USER:$RUN_USER "/input"
chown -R $RUN_USER:$RUN_USER "/output"

##########################
# Exec docker-run script #
##########################
chmod +x /bin/docker-run
exec su -c 'exec /bin/docker-run' $RUN_USER
